# Generated by Django 2.1.5 on 2021-09-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210913_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Page'},
        ),
    ]
