# Generated by Django 2.1.5 on 2021-09-22 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20210919_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 15, 23, 29, 373142, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
